services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"   # Web UI
      - "222:22"      # SSH
    volumes:
      - ./gitea-data:/data
    networks:
      - woodnet

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: always
    ports:
      - "8000:8000"   # Web UI
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea:3000
      - WOODPECKER_GITEA_CLIENT=SEU_CLIENT_ID
      - WOODPECKER_GITEA_SECRET=SEU_CLIENT_SECRET
    volumes:
      - ./woodpecker-data:/var/lib/woodpecker
    networks:
      - woodnet
    depends_on:
      - gitea

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    restart: always
    environment:
      - WOODPECKER_SERVER=http://woodpecker-server:8000
      - WOODPECKER_AGENT_SECRET=SEU_AGENT_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - woodnet
    depends_on:
      - woodpecker-server

networks:
  woodnet:
    driver: bridge
