version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"   # Web UI
      - "222:22"      # SSH
    volumes:
      - ./gitea-data:/data
    networks:
      - woodnet

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: always
    ports:
      - "8000:8000"   # Web UI
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://host.docker.internal:3000
      - WOODPECKER_GITEA_CLIENT=3d29c9c3-2395-4fe1-9ecd-cb675de61c7f
      - WOODPECKER_GITEA_SECRET=gto_ykm6sjjgiqpu3nkl5wwfoft3fe24nykpejy5draz2u27rfoxp6la
    volumes:
      - ./woodpecker-data:/var/lib/woodpecker
    networks:
      - woodnet

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    restart: always
    environment:
      - WOODPECKER_SERVER=http://localhost:8000
      - WOODPECKER_AGENT_SECRET=gto_ykm6sjjgiqpu3nkl5wwfoft3fe24nykpejy5draz2u27rfoxp6la
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - woodnet

networks:
  woodnet:
    driver: bridge
